# Generated by Django 4.0.10 on 2026-04-10 20:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lemon_squeezy_variant_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire this plan.')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bandwidth_limit_bytes', models.BigIntegerField(help_text='Monthly data cap in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('gallery_expiry_days', models.IntegerField(help_text='Days until galleries expire (e.g., 30)', validators=[django.core.validators.MinValueValidator(1)])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('features', models.JSONField(default=list, help_text='List of features for frontend display')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.pricingplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['session_token'], name='checkout_ch_session_127186_idx'),
        ),
    ]
