"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.
"""

import os
import mimetypes
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv  # <-- NEW: Imports the tool that reads the .env file
from django.core.exceptions import ImproperlyConfigured # <-- NEW: Allows the app to crash safely

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# ENTERPRISE ENVIRONMENT LOADER
# ==========================================
# Look one folder up (photobox-api root) for the .env file
env_path = BASE_DIR.parent / '.env'
load_dotenv(dotenv_path=env_path) # This injects the file contents into os.environ!

# ==========================================
# FAIL-FAST PERIMETER (THE SHIELD)
# ==========================================

# 1. DATABASE ARMOR
if not os.environ.get('DB_NAME') or not os.environ.get('DB_PASS'):
    raise ImproperlyConfigured(f"CRITICAL: DB credentials missing. Check your .env file at: {env_path}")

# 2. SECRET_KEY ARMOR
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("CRITICAL: SECRET_KEY is missing from the .env file! System halted to prevent token forgery.")

# 3. THE DEBUG NUKE
DEBUG = bool(int(os.environ.get('DEBUG', 0)))

# THE TRANSPORT: Dynamically pull the frontend URL from the server environment
# (Moved down here so it actually reads the .env file first!)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'user',
    'gallery',
    'core',
    'billing',
    # NEW: Identity Federation Armor
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',

]
# REQUIRED BY ALLAUTH
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DB_HOST'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR / 'static_root'
MEDIA_ROOT = BASE_DIR / 'media_root'

mimetypes.add_type("text/css", ".css", True)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Catch Brute Force attacks
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',  # Hackers guessing passwords get blocked fast
        'user': '1000/day'   # Legitimate users have plenty of API calls
    }
}

SPECTACULAR_SETTINGS = {
    'COMPONENT_SPLIT_REQUEST': True,
}

# --- LOGGING CONFIGURATION ---
# This catches errors and routes them to the console and a file.


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # In production, you would route this to Sentry or CloudWatch
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'core': { # Logs specific to your custom apps
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'gallery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        }
    },
}

# ==========================================
# JWT AUTHENTICATION SETTINGS
# ==========================================
SIMPLE_JWT = {
    # The short-lived "Wristband" (Highly secure, expires fast if stolen)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # The long-lived "ID Card" (Keeps the user logged in without typing their password)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Security: When they use a refresh token, give them a brand new one and kill the old one
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # The HTTP Header format React will use (e.g., "Authorization: Bearer <token>")
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==========================================
# ENTERPRISE SECURITY: PASSWORD HASHING
# ==========================================
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher', # The Gold Standard
    'django.contrib.auth.hashers.PBKDF2PasswordHasher', # The Fallback for legacy
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# ==========================================
# IDENTITY FEDERATION SECURITY RULES
# ==========================================
# 1. We already use SimpleJWT, tell dj-rest-auth to use it too
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'access'
JWT_AUTH_REFRESH_COOKIE = 'refresh'

# 2. Tell Allauth we don't use usernames, only emails
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# 3. THE VAULT FIX: Prevent Blind Social Takeovers
# If a Google login matches an existing email, force them to link manually or block it
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False

# 4. Use our custom User Serializer for registration
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'user.serializers.UserSerializer',
}

# ==========================================
# WINDOWS CSS BUG FIX
# ==========================================



# ENGINEER FIX: Fixes Windows "MIME Type" bug where CSS is treated as plain text
mimetypes.add_type("text/css", ".css", True)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# ENGINEER FIX: Uses BASE_DIR so paths are valid on Windows/Bare-Metal
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

# This tells Django where to look for your own custom CSS/JS files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# LEMON SQUEEZY CONFIG
LEMON_SQUEEZY_WEBHOOK_SECRET = os.environ.get('LEMON_SQUEEZY_WEBHOOK_SECRET')

