"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.
"""

import os
import sys
import mimetypes
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# ENTERPRISE ENVIRONMENT LOADER
# ==========================================
# Look one folder up (photobox-api root) for the .env file
env_path = BASE_DIR.parent / '.env'
load_dotenv(dotenv_path=env_path) # This injects the file contents into os.environ!

# ==========================================
# FAIL-FAST PERIMETER (THE SHIELD)
# ==========================================

# 1. DATABASE ARMOR
if not os.environ.get('DB_NAME') or not os.environ.get('DB_PASS'):
    raise ImproperlyConfigured(f"CRITICAL: DB credentials missing. Check your .env file at: {env_path}")

# 2. SECRET_KEY ARMOR
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("CRITICAL: SECRET_KEY is missing from the .env file! System halted to prevent token forgery.")

# 3. THE DEBUG NUKE
DEBUG = bool(int(os.environ.get('DEBUG', 0)))

# THE TRANSPORT: Dynamically pull the frontend URL from the server environment
# (Moved down here so it actually reads the .env file first!)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,.ngrok.app,.ngrok-free.app').split(',') if host.strip()
]

# Test mode: run Celery tasks synchronously so tests don't need a broker
if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

    # ── CREDENTIAL STUBS ──────────────────────────────────────────────────────
    # Provide safe test defaults for every external service so the perimeter
    # guards never halt the test runner for missing env vars.
    CLOUDFLARE_WEBHOOK_SECRET = os.environ.get('CLOUDFLARE_WEBHOOK_SECRET', 'test-webhook-secret')
    CLOUDFLARE_R2_ENDPOINT    = os.environ.get('CLOUDFLARE_R2_ENDPOINT',    'https://test.r2.cloudflarestorage.com')
    CLOUDFLARE_R2_BUCKET_NAME = os.environ.get('CLOUDFLARE_R2_BUCKET_NAME', 'test-bucket')
    CLOUDFLARE_R2_DOMAIN      = os.environ.get('CLOUDFLARE_R2_DOMAIN',      'test-r2-domain.example.com')
    CLOUDFLARE_ACCESS_KEY_ID  = os.environ.get('CLOUDFLARE_ACCESS_KEY_ID',  'test-key-id')
    CLOUDFLARE_SECRET_ACCESS_KEY = os.environ.get('CLOUDFLARE_SECRET_ACCESS_KEY', 'test-secret-key')
    CLOUDINARY_CLOUD_NAME     = os.environ.get('CLOUDINARY_CLOUD_NAME',     'test-cloud')
    LEMON_SQUEEZY_API_KEY     = os.environ.get('LEMON_SQUEEZY_API_KEY',     'test-ls-api-key')
    LEMON_SQUEEZY_STORE_ID    = os.environ.get('LEMON_SQUEEZY_STORE_ID',    '1')
    LEMON_SQUEEZY_WEBHOOK_SECRET_PRIMARY   = os.environ.get('LEMON_SQUEEZY_WEBHOOK_SECRET_PRIMARY', 'test-ls-webhook-secret')
    LEMON_SQUEEZY_WEBHOOK_SECRET_SECONDARY = os.environ.get('LEMON_SQUEEZY_WEBHOOK_SECRET_SECONDARY', '')

    # ── THROTTLE KILL-SWITCH ──────────────────────────────────────────────────
    # Throttling must be off so security tests aren't randomly 429'd.
    # Individual security tests that VERIFY throttling apply their own throttle
    # by importing and patching the specific throttle class.
    _THROTTLE_OVERRIDE = {
        'DEFAULT_THROTTLE_CLASSES': [],
        'DEFAULT_THROTTLE_RATES': {},
    }

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',              # SECURITY: Strict CORS enforcement
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'user',
    'gallery',
    'core',
    'billing',
    'checkout',
    'ingestion',
    'webhooks',
    # NEW: Identity Federation Armor
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

# REQUIRED BY ALLAUTH
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS MIDDLEWARE: Must be before CommonMiddleware per django-cors-headers docs
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DB_HOST'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR / 'static_root'
MEDIA_ROOT = BASE_DIR / 'media_root'

mimetypes.add_type("text/css", ".css", True)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Global defaults — per-view throttles override these
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',           # Brute force block
        'user': '1000/day',           # General authenticated calls
        'fast_lane_upload': '30/minute',   # Fast Lane binary uploads
        'heavy_lane_ticket': '10/minute',  # Heavy Lane manifest submissions
    }
}

# TEST MODE: Disable throttling globally so security tests aren't randomly 429'd.
# Tests that explicitly VERIFY throttle behaviour patch their own throttle class.
if 'test' in sys.argv:
    REST_FRAMEWORK.update(_THROTTLE_OVERRIDE)



SPECTACULAR_SETTINGS = {
    'COMPONENT_SPLIT_REQUEST': True,
}

# --- LOGGING CONFIGURATION ---
# This catches errors and routes them to the console and a file.


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # In production, you would route this to Sentry or CloudWatch
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_error.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'core': { # Logs specific to your custom apps
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'gallery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        }
    },
}

# ==========================================
# JWT AUTHENTICATION SETTINGS
# ==========================================
SIMPLE_JWT = {
    # The short-lived "Wristband" (Highly secure, expires fast if stolen)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # The long-lived "ID Card" (Keeps the user logged in without typing their password)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Security: When they use a refresh token, give them a brand new one and kill the old one
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # The HTTP Header format React will use (e.g., "Authorization: Bearer <token>")
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==========================================
# ENTERPRISE SECURITY: PASSWORD HASHING
# ==========================================
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher', # The Gold Standard
    'django.contrib.auth.hashers.PBKDF2PasswordHasher', # The Fallback for legacy
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# ==========================================
# IDENTITY FEDERATION SECURITY RULES
# ==========================================
# 1. We already use SimpleJWT, tell dj-rest-auth to use it too
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'access'
JWT_AUTH_REFRESH_COOKIE = 'refresh'

# 2. Tell Allauth we don't use usernames, only emails
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# 3. THE VAULT FIX: Prevent Blind Social Takeovers
# If a Google login matches an existing email, force them to link manually or block it
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False

# 4. Use our custom User Serializer for registration
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'user.serializers.UserSerializer',
}

# ==========================================
# WINDOWS CSS BUG FIX
# ==========================================



# ENGINEER FIX: Fixes Windows "MIME Type" bug where CSS is treated as plain text
mimetypes.add_type("text/css", ".css", True)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# ENGINEER FIX: Uses BASE_DIR so paths are valid on Windows/Bare-Metal
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

# This tells Django where to look for your own custom CSS/JS files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# LEMON SQUEEZY CONFIG
LEMON_SQUEEZY_WEBHOOK_SECRET = os.environ.get('LEMON_SQUEEZY_WEBHOOK_SECRET')


# ==========================================
# CORS: STRICT ORIGIN ALLOWLIST
# ==========================================
# SECURITY: CORS_ALLOW_ALL_ORIGINS must NEVER be True in production.
# Wildcards open the API to credential theft via cross-origin requests.
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',')
    if origin.strip()
]

# Only the headers our API clients need — no wildcard
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ==========================================
# CLOUDFLARE R2 — UNIFIED VAULT
# ==========================================
# IAM credentials are scoped to s3:PutObject + s3:GetObject ONLY.
# Never grant s3:DeleteObject, s3:ListBucket, or s3:PutBucketPolicy from application code.
CLOUDFLARE_R2_BUCKET_NAME = os.environ.get('CLOUDFLARE_R2_BUCKET_NAME', '')
CLOUDFLARE_R2_ENDPOINT = os.environ.get('CLOUDFLARE_R2_ENDPOINT', '')
CLOUDFLARE_ACCESS_KEY_ID = os.environ.get('CLOUDFLARE_ACCESS_KEY_ID', '')
CLOUDFLARE_SECRET_ACCESS_KEY = os.environ.get('CLOUDFLARE_SECRET_ACCESS_KEY', '')

# Public R2 domain for constructing Cloudinary Fetch proxy URLs
# Example: 'pub-<hash>.r2.dev' or your custom verified domain
CLOUDFLARE_R2_DOMAIN = os.environ.get('CLOUDFLARE_R2_DOMAIN', '')

# HMAC secret for validating Cloudflare R2 event notifications
# Must be a cryptographically random string, NOT the same as R2 credentials
CLOUDFLARE_WEBHOOK_SECRET = os.environ.get('CLOUDFLARE_WEBHOOK_SECRET', '')


# ==========================================
# CLOUDINARY — CDN FETCH PROXY ONLY
# ==========================================
# Cloudinary receives NO SDK uploads. It acts as a Transform + Cache layer
# that fetches from R2 on first request and serves WebP to clients.
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')


# ==========================================
# EMAIL DELIVERY
# ==========================================
# In production: replace with SendGrid/SES SMTP credentials from .env
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Console for dev/test
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'PhotoBox <no-reply@photobox.app>')


# ==========================================
# GALLERY RETENTION POLICY (GDPR COMPLIANCE)
# ==========================================
# TTL in days per subscription tier. 0 = unlimited (Enterprise).
# These are enforced by the nightly Celery Beat purge task.
GALLERY_TTL_DAYS = {
    'FREE': 30,
    'PRO': 365,
    'ENTERPRISE': 0,  # 0 = unlimited; manual purge only
}

# GDPR: After expiry, soft-delete. Hard-delete from R2 after this grace period.
GALLERY_HARD_DELETE_GRACE_DAYS = 30


# ==========================================
# DJANGO OOM PROTECTION (Defense Layer 2)
# ==========================================
# Nginx client_max_body_size is Layer 1. This is the Django-level safety net.
# No single request body can consume more than 5MB of server RAM.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024   # 2 MB: files above this go to temp disk


# ==========================================
# CELERY: ASYNC TASK QUEUE
# ==========================================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# ==========================================
# SENTRY: PRODUCTION ERROR MONITORING
# ==========================================
# Set SENTRY_DSN in .env for production. Leave empty for local dev.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
            ),
            CeleryIntegration(monitor_beat_tasks=True),
            LoggingIntegration(
                level=None,           # Capture breadcrumbs from all log levels
                event_level='ERROR',  # Only send ERROR+ to Sentry as events
            ),
        ],
        # Performance monitoring: sample 20% of transactions in production
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.2')),
        # Release tracking for deploy visibility
        release=os.environ.get('APP_VERSION', 'photobox-api@dev'),
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'development'),
        # SECURITY: Strip passwords, tokens, PII from Sentry payloads
        send_default_pii=False,
    )
