# Generated by Django 4.0.10 on 2026-04-15 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_workspace_storage_limit_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding'), ('CORPORATE', 'Corporate Event'), ('GOVERNMENT', 'Government / Official'), ('NGO', 'NGO / Non-Profit'), ('PRIVATE', 'Private Function'), ('SPORTS', 'Sports / Action'), ('STUDIO', 'Studio / Portrait'), ('COMMERCIAL', 'Commercial / Brand Campaign'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('_hashed_pin', models.CharField(blank=True, db_column='hashed_pin', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='gallery.event')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('r2_object_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('optimized_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_file', models.FileField(blank=True, max_length=255, null=True, upload_to='events/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('blurhash', models.CharField(blank=True, help_text='Base64 LQIP string', max_length=100, null=True)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.scene')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('event', 'title'), name='unique_scene_per_event'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['scene', 'is_processed'], name='gallery_pho_scene_i_5e758f_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['scene', 'status'], name='gallery_pho_scene_i_132af8_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_event_slug_per_workspace'),
        ),
    ]
