# Generated by Django 4.0.10 on 2026-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_dimensions_event_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Upload'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('QUARANTINED', 'Quarantined — Size Mismatch'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
