# Generated by Django 4.0.10 on 2026-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
