# Generated by Django 4.0.10 on 2026-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_file_size_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_limit_gb',
            field=models.IntegerField(default=1),
        ),
    ]
