# Generated by Django 4.0.10 on 2026-04-15 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_storage_limit_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=1073741824, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workspace',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
