# Generated by Django 4.2.30 on 2026-09-03 02:50

import core.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_legacy_gallery_models'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workspace',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
